### ISSUE TITLE
[BUG] type here a short description

### ISSUE THREAD

**Issue by JemmaSinclair** [citizenfx/txAdmin#780] opened 2023-03-12 20:34 UTC
**txAdmin/FXServer versions:**
v5.2.0 atop FXServer 6302
  
**Describe the bug**
When exiting spectate it will stay on a black screen for an inconsistent amount of time.

**To Reproduce**
Spectate a user outside of onesync range.
Exit spectate.
Wait.

**Expected behavior**
Return you back to where you were within less than a minute.

**Screenshots**
_It was going on for about 10 minutes prior to this._
![image](https://user-images.githubusercontent.com/61020381/224571797-0f180505-a58a-4ec9-9970-cb06b2c3c63e.png)
![image](https://user-images.githubusercontent.com/61020381/224571924-1fb60b5c-8b78-4316-bc2d-737309de55ed.png)
Refer to time in windows taskbar.
**Additional context**
OS: Ubuntu 20.04

**Comment by tabarra** [comment] 2023-03-12 20:35
Duplicate of #548

**Closed as completed by tabarra** 2023-03-12 20:35 UTC
