### ISSUE TITLE
[BUG] Noclip effect showing on random players

### ISSUE THREAD

**Issue by GeerdoDaGr8** [citizenfx/txAdmin#564] opened 2022-01-17 22:16 UTC
This issue has been going on for some time and I didnt report it as i thought it would be fixed on an update but its been serveral now and I am on the most recent and it is still happening.
(https://clips.twitch.tv/ExcitedQuaintButterTebowing-YTp9EcwD-XD0WPq2)
We keep having this happen to random people when staff is no clipping it will randomly put that effect one someone in the city

**Comment by tabarra** [comment] 2022-02-15 21:01
Duplicate of #559

**Closed as completed by tabarra** 2022-02-15 21:01 UTC
