### ISSUE TITLE
Suggestion: Saving all identifiers

### ISSUE THREAD

**Issue by IqFiskMos** [citizenfx/txAdmin#328] opened 2021-04-22 14:01 UTC
It would be nice so be able to save allt identifiers for a player not just the license when they are offline.
When they play i can see all but not when offline. Please make it possible to save them all

Player Identifiers:
steam:,
license:,
xbl:,
live:,
discord:,
fivem:

**Comment by czsquizer** [comment] 2021-04-22 20:49
It would be cool, but ...

**Comment by n0tsiege** [comment] 2021-04-22 22:18
Your best bet would be to open a Pull Request with this code as the commit, if you know how 🙂

**Comment by tabarra** [comment] 2022-03-26 09:38
This will be done, for now I'm closing this as duplicate of #385, thanks for the suggestion.

**Closed as completed by tabarra** 2022-03-26 09:38 UTC
Labels: enhancement
