### ISSUE TITLE
NoClip Teleporting

### ISSUE THREAD

**Issue by chrislenga** [citizenfx/txAdmin#402] opened 2021-07-15 17:25 UTC
I'm not sure if this is intended, but it's horribly inconvenient if so. We cannot seem to teleport while noclipped. This forces us to land somewhere, or break noclip and then tp, then reactivate noclip. If this is intended, can this be a setting server owners can toggle?

**Comment by tabarra** [comment] 2021-07-15 17:31
In the TODO list.  
I also want to make sure that if you leave noclip, you don't fall to your death. Getting out of noclip if you are not super super close to the ground is also annoying.

**Comment by TasoOneAsia** [comment] 2021-09-09 03:52
Duplicate of #423

**Closed as completed by TasoOneAsia** 2021-09-09 03:52 UTC
