### ISSUE TITLE
[BUG] Recipe doesn't deploy correctly

### ISSUE THREAD

**Issue by BestRazer** [citizenfx/txAdmin#543] opened 2021-12-21 22:39 UTC
**txAdmin/FXServer versions:**
txAdmin: v4.10.0
  
**Describe the bug**
When trying to deploy a recipe, this error appears in the console:
`[txAdmin:WebServer:anonym] [txAdmin v4.10.0] Route timed out: /deployer/recipe/setVariables`

**To Reproduce**
1. Create a new server
2. Choose QBCore or any other popular template
3. Configure the key and database
4. Click on 'Save'
5. The error should appear in the console

**Expected behavior**
The recipe should be deployed and the QBCore framework should be installed.

**Screenshots**

**Additional context**
The server is hosted on a pterodactyl panel.

**Comment by tabarra** [comment] 2021-12-24 16:02
Could not reproduce.

**Comment by tabarra** [comment] 2022-03-26 10:32
I'm closing this due to no other reports matching this description.  
If you have any new information feel free to provide here.

**Closed as completed by tabarra** 2022-03-26 10:32 UTC

**Comment by Deadgaminglive** [comment] 2022-04-13 18:38
im having this same issue

**Comment by Deadgaminglive** [comment] 2022-04-13 18:38
did you find a fix?
