### ISSUE TITLE
[BUG] Player Ban by Server Log when he's no longer online

### ISSUE THREAD

**Issue by BlackBhul** [citizenfx/txAdmin#603] opened 2022-03-20 17:40 UTC
BUG: When you ban someone by pressing him in the server log page **and he's no longer online**, it bans only the license and not all the identifiers.

![Cattura](https://user-images.githubusercontent.com/65976935/159175229-8a9e1dc1-a793-4b65-aa94-89d2b588f929.JPG)

**Comment by tabarra** [comment] 2022-03-26 11:23
Thanks for the bug report, which is mostly a "missing feature" actually.  
So I'll mark this as duplicate of #385.  
Thanks for the report.

**Closed as completed by tabarra** 2022-03-26 11:23 UTC
