### ISSUE TITLE
[FEATURE]: warn players that are not in the server in player list of txAdmin

### ISSUE THREAD

**Issue by djraymond1** [citizenfx/txAdmin#871] opened 2023-09-07 14:02 UTC
### Scope

Web, In-Game Menu

### Feature Description

![image](https://github.com/tabarra/txAdmin/assets/100388914/1cc21a3d-4178-4d16-be48-844e49ea6f3f)

![image](https://github.com/tabarra/txAdmin/assets/100388914/687a2790-82b1-4568-8a2b-efef05a18e2f)

add a warn option for players

### Use Case

so when there is a player that you forgot to give a warn that you can warn them if they are ofline

### Proposed Solution

![image](https://github.com/tabarra/txAdmin/assets/100388914/687a2790-82b1-4568-8a2b-efef05a18e2f)

add warn tab

**Comment by DetErDugget** [comment] 2023-10-24 13:14
I know the team is speculating how to visualize an offline warning.

Why not just wait for the player to be active and wait 30 sek to send the warning, with the possibility to disable the offline warning visualization and edit the wait timer?

As a server owner, i feel like this is the only thing txadmin is lacking really. :D

**Comment by tabarra** [comment] 2023-10-27 11:48
Duplicate of #522, but I do appreciate the detailed post. Thanks.

**Closed as completed by tabarra** 2023-10-27 11:48 UTC
Labels: enhancement
