### ISSUE TITLE
[FEATURE]: Adding kicking all players as a separate permission

### ISSUE THREAD

**Issue by StevensTheDev** [citizenfx/txAdmin#885] opened 2023-11-29 19:59 UTC
### Scope

Web, In-Game Menu

### Feature Description

It would be very beneficial to add a separate permission box for kicking all players. The goal of this is to separate the power to just kick, and to kick all players. 

### Use Case

We have members of our Administration team that we trust to handle just regular kicks, and we would prefer to limit the ability to kick the whole server to a more limited amount of people.

### Proposed Solution

The proposed solution would be to separate out the permissions of individually kicking vs kicking all players.

### Additional Info

N/A

**Comment by Mycroft-Studios** [comment] 2023-11-29 20:24
> The proposed solution would be to separate out the permissions of individually kicking vs kicking all players.

this would do nothing though. if u can kick, u can kick everyone anyway, by just doing 1 by 1 down the list.

**Comment by tabarra** [comment] 2023-11-30 02:37
Thanks for the request.  
Although this doesn't make much sense, this has been asked so so so many times that i might do it just to comfort the owners that feel like this is actually necessary.  
Either ways i'm closing this as a duplicate of #379

**Closed as completed by tabarra** 2023-11-30 02:37 UTC
Labels: enhancement
