### ISSUE TITLE
[FEATURE]: Staff icon in player list

### ISSUE THREAD

**Issue by napei** [citizenfx/txAdmin#638] opened 2022-06-05 06:23 UTC
### Scope

Web

### Feature Description

Provide a staff icon in front of the ID in the player list for the web portal to show staff members who are online.

### Proposed Solution

By placing the shield before the ID number, this can differentiate between players that have this emoji in their name as well to pretend to be staff.

![image](https://user-images.githubusercontent.com/8946502/172038144-6c3fa8f9-1a7a-4121-9239-a9b175f4c424.png)

This was with:
```css
.pping:before {
  content: '🛡️';
}
```

**Comment by TasoOneAsia** [comment] 2022-11-27 18:27
Implemented with v4.8.0

**Comment by tabarra** [comment] 2022-11-27 18:38
The issue is about the Web UI though, we only have it for the menu.

**Comment by TasoOneAsia** [comment] 2022-11-27 18:40
@tabarra whoops, want me to implement for Web UI real quick?

**Comment by tabarra** [comment] 2022-11-27 18:43
Meh this one we will have a hard time solving well without the React refactor, so for now probably better to leave it be.

**Comment by tabarra** [comment] 2023-09-05 03:37
Since I included this in #628, I'll close this as a duplicated.

**Closed as completed by tabarra** 2023-09-05 03:37 UTC
Labels: enhancement
