### ISSUE TITLE
API to ban a player.

### ISSUE THREAD

**Issue by abhishekdeshkar** [citizenfx/txAdmin#286] opened 2021-02-16 04:20 UTC
Is it possible to ban a player remotely ? And also is it possible to use MySQL instead of playersDB.json ?

**Comment by tabarra** [comment] 2021-02-16 04:22
Duplicate of #179

**Closed as completed by tabarra** 2021-02-16 04:22 UTC

**Comment by PLOKMJNB** [comment] 2021-02-16 04:30
Also how do you mean remotely? If you opened the port you can use txAdmin from anywhere with the IP. I've even opened and used txAdmin on my car
